### ISSUE TITLE
bug related to identical usernames

### ISSUE THREAD

**Issue by oiy136** [dz-root/Root-me-diff#3]
<h1>
[Exemple link](https://root-me-diff.vercel.app/diff?user_1=Almandin-746451&user_2=oiy)
</h1>

When on display, if I click on almandin' s profile picture , it sends me to almandin' s profile 
( https://www.root-me.org/Almandin)  but without the "-746451"

Good link : https://www.root-me.org/Almandin-746451

**Comment by dz-root** [comment]
Hi Oiy thank you for your reporting. Indeed some root-me.org users have an id when the username is duplicated.
For example:
nickname 1: Almandin Slug: Almandin-74645
nickname 2: Almandin Slug: Almandin

The link to user profile was based on user nickname. it's fixed now.
